### PR TITLE
Set optimisation on ARM to -O0, which stops tests from hanging.

### PR DESCRIPTION
**Pull request by simonbyrne**

### CODE REVIEW

**Comment by tkelman** [comment]
ref https://github.com/JuliaLang/openlibm/pull/111, would `-fno-builtin` help?

**Comment by eschnett** [comment]
You could add a comment such as "TODO: look into this further", maybe with a pointer to this issue. Presumably, if there is someone with interest and experience and time at hand, this someone might want to remove the `-O0` again.

**Comment by simonbyrne** [comment]
It appears to be a problem with `rint` and `nearbyint` (and their related functions). I've just disabled optimisations for these (#116).

Note that these aren't used in Julia itself (it uses the LLVM intrinsics for such functions, which most of the time will be lowered straight to native instructions).

**Comment by ViralBShah** [comment]
Also, @edelsohn mentioned that GCC 5 has fenv controls for most targets, so we should be able to gradually be able to get rid of `-O0`.

**Pull request merged**
