### PR TITLE
test: append $(CFLAGS_add), which includes fno-builtin

### PR DESCRIPTION
**Pull request by iblis17**
Is there any undesired side effect?

### CODE REVIEW

**Comment by staticfloat** [comment]
What was in `CFLAGS_arch`?  Can you post the output of `make print-CFLAGS_arch` and `make print-CFLAGS_add` on your system?

For reference, this is what is shown on my Linux x86_64 system:
```
$ make print-CFLAGS_add
CFLAGS_add=-fno-gnu89-inline -fno-builtin -O3 -fPIC -m64 -std=c99 -Wall -I/home/sabae/src/openlibm -I/home/sabae/src/openlibm/include -I/home/sabae/src/openlibm/amd64 -I/home/sabae/src/openlibm/src -DASSEMBLER -D__BSD_VISIBLE -Wno-implicit-function-declaration -I/home/sabae/src/openlibm/ld80
$ make print-CFLAGS_arch
CFLAGS_arch=-m64

```

**Comment by iblis17** [comment]
```
└─[iblis@abeing Oops]% gmake print-CFLAGS_arch
CFLAGS_arch=-m64
┌─[~/git/openlibm]
| [Venv(py36)] [ test-cflags] [-- INSERT --]
└─[iblis@abeing]% gmake print-CFLAGS_add
CFLAGS_add=-fno-builtin -O3 -fPIC -m64 -std=c99 -Wall -I/usr/home/iblis/git/openlibm -I/usr/home/iblis/git/openlibm/include -I/usr/home/iblis/git/openlibm/amd64 -I/usr/home/iblis/git/openlibm/src -DASSEMBLER -D__BSD_VISIBLE -Wno-implicit-function-declaration -I/usr/home/iblis/git/openlibm/ld80
┌─[~/git/openlibm]
| [Venv(py36)] [ test-cflags] [-- INSERT --]
└─[iblis@abeing]% uname -a
FreeBSD abeing 12.0-CURRENT FreeBSD 12.0-CURRENT #4 r309367: Mon Dec 12 11:10:09 CST 2016     root@abeing:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by staticfloat** [comment]
Hmmm, it looks like there are some problems, this is probably due to the `-O3` being passed in.  It might be worthwhile seeing if eliminating the `-O3` from the flags gets the test suite to pass.

**Comment by iblis17** [comment]
combime `-fno-builtin` and `-OX` can pass test on my amd64 machine.

I think that we should test both with and without `-OX`, since user of openlibm can add the `-OX` flags if they want. I believe optimizing with `-O` is always safe and the unsafe/experimental optimization will be named flags in clang/gcc.

**Comment by staticfloat** [comment]
If I'm interpreting this correctly, we have had a fairly serious bug in our test suite for a while.  In essence, we _definitely_ should have had `-fno-builtin` applied to the testing functions, as without it, our testing routines are apparently using the builtin `libm` implementations!  To demonstrate this, if you add `-fno-builtin-ynf` to the `test-float` compilation, this test fails.  (That's the only flag needed to cause it to fail).

Looking at the disassembly for this routine, without `-fno-builtin-ynf`, for [this line](https://github.com/iblis17/openlibm/blob/106099d70c95dbdc5e44ef321f1be07333512ffb/test/libm-test.c#L4214) we get:
```
0x080593c8 <+1712>:  movl   $0x0,0x14(%esp)
0x080593d0 <+1720>:  movl   $0x0,0x10(%esp)
0x080593d8 <+1728>:  fld1
0x080593da <+1730>:  fstps  0xc(%esp)
0x080593de <+1734>:  flds   0x80608f0
0x080593e4 <+1740>:  fstps  0x8(%esp)
0x080593e8 <+1744>:  flds   0x80608f0
0x080593ee <+1750>:  fstps  0x4(%esp)
0x080593f2 <+1754>:  movl   $0x80602bc,(%esp)
0x080593f9 <+1761>:  call   0x8049ee5 <check_float>
```

Notice how there's no call to `ynf` here.   However, if we include `-fno-builtin-ynf`, we disassemble to:
```
0x080594e0 <+1992>:  flds   0x806072c
0x080594e6 <+1998>:  fstps  0x4(%esp)
0x080594ea <+2002>:  movl   $0x3,(%esp)
0x080594f1 <+2009>:  call   0x80490b0 <ynf@plt>
0x080594f6 <+2014>:  movl   $0x0,0x14(%esp)
0x080594fe <+2022>:  movl   $0x0,0x10(%esp)
0x08059506 <+2030>:  fld1
0x08059508 <+2032>:  fstps  0xc(%esp)
0x0805950c <+2036>:  flds   0x8060a68
0x08059512 <+2042>:  fstps  0x8(%esp)
0x08059516 <+2046>:  fstps  0x4(%esp)
0x0805951a <+2050>:  movl   $0x806043c,(%esp)
0x08059521 <+2057>:  call   0x8049ee5 <check_float>
```

This is really, really, bad, as it means that, at least on some platforms, the compiler has been happily calculating these functions with its own `libm`, and embedding the answers into our test suites.

Luckily, it looks like our mathematical functions are (almost) correct!  We're only 1 `ulp` off on most of them, which is close enough for me to accept this.  Just bump the tolerances up an `ulp`:

```
diff --git a/test/libm-test-ulps.h b/test/libm-test-ulps.h
index fa630ed..4a0c783 100644
--- a/test/libm-test-ulps.h
+++ b/test/libm-test-ulps.h
@@ -243,12 +243,12 @@
 #define DELTA1651 CHOOSE(1, 1, 2, 1, 1, 2)     /* yn (1, 2.0) == -0.10703243154093754689  */
 #define DELTA1652 CHOOSE(2, 1, 2, 2, 0, 2)     /* yn (1, 8.0) == -0.15806046173124749426  */
 #define DELTA1653 CHOOSE(0, 3, 2, 0, 3, 2)     /* yn (1, 10.0) == 0.24901542420695388392  */
-#define DELTA1656 CHOOSE(2, 1, 1, 2, 1, 1)     /* yn (3, 0.1) == -5099.3323786129048894  */
+#define DELTA1656 CHOOSE(2, 1, 2, 2, 1, 1)     /* yn (3, 0.1) == -5099.3323786129048894  */
 #define DELTA1657 CHOOSE(2, 3, 1, 2, 3, 1)     /* yn (3, 0.7) == -15.819479052819633505  */
 #define DELTA1659 CHOOSE(0, 1, 1, 0, 1, 1)     /* yn (3, 2.0) == -1.1277837768404277861  */
 #define DELTA1660 CHOOSE(0, 1, 1, 0, 1, 1)     /* yn (3, 10.0) == -0.25136265718383732978  */
 #define DELTA1663 CHOOSE(2, 2, 2, 2, 2, 1)     /* yn (10, 0.1) == -0.11831335132045197885e19  */
 #define DELTA1664 CHOOSE(7, 6, 3, 7, 6, 3)     /* yn (10, 0.7) == -0.42447194260703866924e10  */
-#define DELTA1665 CHOOSE(0, 1, 1, 0, 1, 1)     /* yn (10, 1.0) == -0.12161801427868918929e9  */
+#define DELTA1665 CHOOSE(0, 1, 2, 0, 1, 1)     /* yn (10, 1.0) == -0.12161801427868918929e9  */
 #define DELTA1666 CHOOSE(1, 2, 1, 1, 2, 1)     /* yn (10, 2.0) == -129184.54220803928264  */
 #define DELTA1667 CHOOSE(0, 2, 1, 0, 2, 1)     /* yn (10, 10.0) == -0.35981415218340272205  */
```

**Comment by iblis17** [comment]
@staticfloat that's why I highlight https://github.com/JuliaLang/openlibm/issues/10#issuecomment-173203675 and ask the test answer from (on slack).

**Comment by staticfloat** [comment]
@iblis17 if you modify the `ulp` factors as I outlined above, I will happily merge this.  This is the last change I'd like to get in before cutting a new release.

**Comment by iblis17** [comment]
@staticfloat done :)

**Comment by staticfloat** [comment]
Okay, one more ulp-bump; we need to take `yn (10, 2.0)` and bump it up to `3` instead of `2`, as shown by the tests for `aarch64` and `ppc64le`.

**Comment by iblis17** [comment]
CI looks happy now

**Comment by staticfloat** [comment]
Great, thanks @iblis17!

**Pull request merged**
