### PR TITLE
Test Linux amd64/i686/arm64

### PR DESCRIPTION
**Pull request by petercolberg**
Create a clean, minimal, cross-platform Travis script with a build matrix for testing different operating systems and architectures. The tests include Linux amd64, i686, and arm64, which is tested using qemu user emulation.

### CODE REVIEW

**Comment by petercolberg** [comment]
This merge request is ready for your review. Apart from significantly increasing the number of tested architectures, this work provides a stable basis for testing futher platforms and compilers. I will submit a separate merge request for Linux arm hard-float later, which currently fails the tests due to lacking floating-point exceptions. In any case, the arm-specific code is now tested (successfully) on arm64.

@staticfloat, after #139 has been merged, please rebase #133 [WIP] for OS X and clang testing.

**Comment by staticfloat** [comment]
This is great, @petercolberg.  Am I understanding correctly that the `binfmt` kernel extension allows the linux kernel to load an AArch64 executable and run it within `qemu` transparently?  If so, that is incredibly slick.

**Comment by petercolberg** [comment]
It is slick indeed, I was enthused to find that emulation is completely transparent. I am grateful in part to the Debian developers that made this an out of the box experience by providing qemu binaries, cross compilers and cross libc packages for a great number of architectures :wink:.

**Comment by staticfloat** [comment]
Indeed.  This looks good to me and is fairly innocuous so I'm just gonna merge it.

**Comment by tkelman** [comment]
Yes, good stuff. The override and the header change are a little bit risky but we'll see when we first try to change Julia across all platforms to use an openlibm tag that has these changes included.

**Pull request merged**
