### PR TITLE
Fix compilation on AArch64

### PR DESCRIPTION
**Pull request by yuyichao**
The 128bit double directory is missing and was never used....

### CODE REVIEW

**Comment by nalimilan** [comment]
Can we tag a new release? I won't be able to include 0.5.5 in Fedora as long as it doesn't build on Aarch64.

**Comment by ginggs** [comment]
Ping?  Same applies to Debian.

**Comment by CDLuminate** [comment]
+1 request for tagging a new release.

**Comment by ginggs** [comment]
I created a PR #180.

**Pull request merged**
