### PR TITLE
[WIP] More makefile improvements

### PR DESCRIPTION
**Pull request by petercolberg**
I am going over the patches in the openlibm Debian package to see which ones are useful to integrate into upstream openlibm.

### CODE REVIEW

**Comment by petercolberg** [comment]
Sorry for not being clear, WIP stands for work in progress…

**Comment by petercolberg** [comment]
Could you undo the merge?

**Comment by ViralBShah** [comment]
Of course. Didn't see that. I think I can only revert it for now. I have also sent you commit access so you could do it as well.

**Comment by petercolberg** [comment]
You can revert the merge using
```
git push origin -f 4c8740a:master
```
as long as noone has fetched so far, which is reasonable to assume but should remain the absolute exception.

**Comment by ViralBShah** [comment]
It's a protected branch, it turns out. If you don't mind, we can revert, or do a new PR for the remaining things.

**Comment by petercolberg** [comment]
I noticed the protected branch. That is good practice anyway.

Then please leave it as is. The commit itself is good, I was just going to add more related commits to the pull request.

**Comment by nalimilan** [comment]
Are we sure this `-O3` flag is really useful as a default? My understanding is that it's very rarely a good idea, and should only be applied when benchmarking shows a real improvement.

**Comment by nalimilan** [comment]
Also, @ViralBShah, could you add @petercolberg and @xyproto (for Arch) to the packagers team? I just discovered this allows CCing all team members by writing `@JuliaLang/distro-packagers `.

**Comment by ViralBShah** [comment]
I think `-O2` should be good.

**Comment by ViralBShah** [comment]
Done.

**Pull request merged**
