### PR TITLE
[WIP] Test linux clang on Travis

### PR DESCRIPTION
**Pull request by staticfloat**
This will look like only one commit once https://github.com/JuliaLang/openlibm/pull/132 is merged

### CODE REVIEW

**Comment by staticfloat** [comment]
I know you're a fast reactor @tkelman, but commenting on my PR before I even open it?  That's just plain impressive.

screen shot 2016-04-26 at 8 51 14 pm

**Comment by tkelman** [comment]
had email open?

**Comment by Keno** [comment]
Needs rebase if still relevant.

**Comment by staticfloat** [comment]
I've attempted a rebase, let's see if these tests pass.

**Comment by tkelman** [comment]
so this includes #132, right? are the tolerance changes here still somewhat controversial? cc @simonbyrne

**Comment by simonbyrne** [comment]
Seems fine as a stopgap, would be nice to have a more complete solution though.

**Comment by Keno** [comment]
Bump

**Comment by staticfloat** [comment]
Looks like we're all set to merge if @simonbyrne doesn't have any more immediate concerns.

**Comment by simonbyrne** [comment]
LGTM

**Comment by staticfloat** [comment]
Merged! Good work guys.

**Pull request merged**
