### PR TITLE
Remove non-standard functions from OpenLibm

### PR DESCRIPTION
**Pull request by EdSchouten**
Hi Viral,

As mentioned in issue #79, I promised to send you a pull request to remove non-standard functions from OpenLibm, as they are only needed to keep existing implementations working. New implementations shouldn't offer them. This is how far I got.

Thanks,
Ed

### CODE REVIEW

**Comment by ViralBShah** [comment]
Thank you!

**Comment by simonbyrne** [comment]
Apparently julia still calls `significand` and `signficandf`: 
https://github.com/JuliaLang/julia/blob/1ec68b3173146178ec4f8340b7d2490d4164a4b8/base/math.jl#L135-L141

It would be fairly easy to implement these in Julia.

**Comment by ViralBShah** [comment]
I hadn't checked which of these we were using, but the 0.4.1 release of openlibm that we use for now still has these, so julia is safe. For the 0.5 release of openlibm, we will have to update julia too.

**Comment by nalimilan** [comment]
We're also going to have to bump the SOVERSION major number if we remove functions from the ABI. Better do it in this PR before we forget.

**Comment by ViralBShah** [comment]
Already done in 763da446063bae2ccaff1893ba600739979c3ef3

**Comment by tkelman** [comment]
We should put the single precision bessel functions back. Julia is using them and it doesn't hurt anything to have them in the library. The fact that a standard doesn't mention them is an omission in the standard. https://github.com/JuliaLang/julia/pull/13868

**Comment by ViralBShah** [comment]
I have been putting such things in openspecfun. I guess we could perhaps have a flag in openlibm that allows extra stuff too. However, seems like @yuyichao has a pure julia solution, which is perhaps even better.

**Comment by yuyichao** [comment]
The pure julia implementation is pretty close in performance but is statistically significantly slower than the openlibm or libm implementation (which are the same one AFAICT....) by ~30%. Using `muladd` bring that down to ~15%.

I think this is a pretty fun exercise and probably also a useful benchmark to have but I also agree with Tony that there's little point of writing this in julia if the C version is already working and widely tested. It might make sense to ship a julia version if it can beat the C performance or if it provides other benefit.

**Comment by ViralBShah** [comment]
Agree. Just need a little bit more engg on the openlibm side for this. If we have an extensions flag in openlibm, we can even move rem_pio2 back from openspecfun back here.

**Comment by tkelman** [comment]
Hasn't `USE_SYSTEM_LIBM` been passing? So glibc libm has these single precision bessel fcns? If that's the case I don't see why we would need an extensions flag. We can eventually move this kind of thing to a SpecialFunctions.jl with both Julia and C/Fortran implementations available, for example nolta's translation of Amos would help portability to systems that don't have fortran compilers. I should check whether MSVC supports these single precision Bessel fcns.

**Comment by ViralBShah** [comment]
I believe they are not part of the (C?) spec, but perhaps commonly implemented? 

The flag should just be a couple of lines in Makefile. So, if we reinstate these, it should be straightforward to have a flag.

**Comment by EdSchouten** [comment]
The `double` versions are part of the X/Open UNIX specification, not the C standard. Versions for `float` and `long double` are not part of any standard.

**Comment by yuyichao** [comment]
> Versions for float and long double are not part of any standard.

Which is not a very convincing reason for not implementing them or even removing them from a existing library.

**Comment by tkelman** [comment]
@ViralBShah no tagging openlibm until single-precision bessel gets put back

**Comment by ViralBShah** [comment]
I guess all we need to do is revert https://github.com/JuliaLang/openlibm/commit/8c8693cf7962be7b0e53c491287aeb2fb13ae6f2

**Comment by tkelman** [comment]
And there have been upstream bugfixes in https://github.com/freebsd/freebsd/commit/0563b7a42b5b5f9ab2af93daf62bfed48fb84e55 and several other commits, but if those bugs aren't causing test failures in Julia then they aren't necessarily release blocking.

**Comment by ViralBShah** [comment]
4c8740ad589fd243eb2d3691f2c2395b505d713d fixes this. I'd still like to bring in the EXTENSIONS build flag, but this should be good for now to tag.

**Pull request merged**
