### PR TITLE
Fix Clang warnings on Windows

### PR DESCRIPTION
**Pull request by Keno**
- Align DLLEXPORT in definitions and declations. There is still a few
  cases left, where the declation in the compiler's complex.h disagrees
  with the implementation here. For now we can't do anything about that,
  but maybe should be revisited in the future.
- Fix the syntax on an .ascii directive that gcc accepted mistakingly, but
  clang does not.

### CODE REVIEW

**Comment by tkelman** [comment]
We should probably be using `OLM_DLLEXPORT` here to avoid collisions.

**Comment by ViralBShah** [comment]
Does this warrant a new point release when merged?

**Comment by nalimilan** [comment]
> Does this warrant a new point release when merged?

Maybe check whether we want to do something about https://github.com/JuliaLang/openlibm/issues/127 first?

**Comment by Keno** [comment]
> We should probably be using OLM_DLLEXPORT here to avoid collisions.

Yes, I agree. Will do the rename.

**Pull request merged**
